### PR TITLE
feat(search-page): style

### LINKED ISSUE #207: style(recipe-search): improve search page styling (SMALL)

### PR DESCRIPTION
**Pull request by FangchengDou**
filter style
close #207

### CODE REVIEW

**Comment by FangchengDou** [comment]
Feel free to give me advice on style or other.

**Review by jbutera94 — APPROVED** [review]
Looks good. The only suggestion I would give is maybe having the footer be forced on the bottom of the page. If that's too difficult though (I know stickied elements are hard), no worries.

**Comment by FangchengDou** [comment]
I will try to do footer in another branch and issue

**Comment by jbutera94** [comment]
Sounds good, and that can definitely be a lower priority issue.

**Pull request merged**
